# Generated by Django 6.0.3 on 2026-03-23 02:25

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distillation', models.CharField(max_length=255)),
                ('full_content', models.TextField()),
                ('distillation_sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('full_content_sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
