# Generated by Django 6.0.3 on 2026-03-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manual__bootstrap_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmemory',
            name='content',
        ),
    ]
