# Generated by Django 6.0.3 on 2026-03-23 22:56

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manual__pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distillation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_datetime'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_datetime'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='eventmemory',
            options={},
        ),
    ]
