# Generated by Django 6.0.3 on 2026-03-24 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_drop_eventmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillation',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distillations', to='core.memory'),
        ),
    ]
