# Generated by Django 6.0.3 on 2026-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_distillation_is_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
